# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0012_auto_20161001_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', tinymce.models.HTMLField(null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('content_blocks', models.ManyToManyField(blank=True, null=True, to='base.ContentBlock')),
                ('facilitators', models.ManyToManyField(blank=True, to='base.Facilitator')),
                ('tools', models.ManyToManyField(blank=True, to='base.Tool')),
                ('trainings', models.ManyToManyField(blank=True, to='base.Training')),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
    ]
