# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='content_blocks',
            field=models.ManyToManyField(blank=True, to='base.ContentBlock'),
        ),
    ]
