# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_in_use',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_on_view',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
