# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
