# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160927_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='tools',
            field=models.ManyToManyField(blank=True, to='base.Tool'),
        ),
        migrations.AlterField(
            model_name='training',
            name='facilitators',
            field=models.ManyToManyField(blank=True, to='base.Facilitator'),
        ),
        migrations.AlterField(
            model_name='training',
            name='tools',
            field=models.ManyToManyField(blank=True, to='base.Tool'),
        ),
    ]
