# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160927_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='caption',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_in_use',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_on_view',
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('use', 'In Use'), ('view', 'On View'), ('future', 'Future Tool')], default='use', max_length=8),
        ),
        migrations.AddField(
            model_name='training',
            name='link',
            field=models.URLField(default='test.com'),
            preserve_default=False,
        ),
    ]
