# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160927_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
