# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contentblock_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(null=True, upload_to='tools'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
