# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160928_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='facilitator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['date', 'name']},
        ),
        migrations.AddField(
            model_name='tool',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='made_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
