# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('base', '0013_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('link', models.URLField()),
                ('readings', models.ManyToManyField(blank=True, to='base.Reading')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='texts'),
        ),
        migrations.AddField(
            model_name='practice',
            name='tools',
            field=models.ManyToManyField(blank=True, to='base.Tool'),
        ),
        migrations.AddField(
            model_name='practice',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='base.Training'),
        ),
    ]
