# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170414_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='is_on_main_site',
            field=models.BooleanField(default=True),
        ),
    ]
