# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_contentblock_is_on_main_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Contributor',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='group',
            new_name='contributor',
        ),
    ]
