# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 15:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170820_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bio',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
