# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_contributor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
