# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20170820_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Practice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
