# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_practicepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepdf',
            name='name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
