# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_practicepdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='contributor',
        ),
        migrations.AddField(
            model_name='practice',
            name='contributors',
            field=models.ManyToManyField(to='base.Contributor'),
        ),
    ]
