# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-02 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20170820_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='base.Contributor'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
